/** Central Tailwind config for biozone_web (replaces 10 per-page tailwind.config blocks + Play CDN).
 * Union of all page configs, verified conflict-free. Content covers every
 * template/partial including JS-built class strings (all live in .html).
 */
module.exports = {
  darkMode: "class",
  content: ["./biozone_web/www/**/*.html", "./biozone_web/templates/**/*.html"],
  theme: {
    extend: {
      colors: {
        "alert-bg": "#ffdad6",
        "alert-red": "#ba1a1a",
        "amber-text": "#92400e",
        "appBg": "#f8fafd",
        "background": "#f8f9ff",
        "borderSubtle": "#e2e8f0",
        "darkNavy": "#0b1c30",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#6bd8cb",
        "inverse-surface": "#213145",
        "navy-text": "#0b1c30",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#f4fffc",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626567",
        "on-secondary-fixed": "#191c1e",
        "on-secondary-fixed-variant": "#444749",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#3d4947",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fefcff",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#3f465c",
        "outline": "#6d7a77",
        "outline-variant": "#bcc9c6",
        "primary": "#00685f",
        "primary-accent": "#008378",
        "primary-container": "#008378",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "primary-hover": "#00544d",
        "primary-light": "#e6f3f2",
        "secondary": "#5c5f61",
        "secondary-container": "#e0e3e5",
        "secondary-fixed": "#e0e3e5",
        "secondary-fixed-dim": "#c4c7c9",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface-subtle": "#eff4ff",
        "surface-tint": "#006a61",
        "surface-variant": "#d3e4fe",
        "surfaceMuted": "#f1f5f9",
        "tertiary": "#545c72",
        "tertiary-container": "#6c748b",
        "tertiary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#bec6e0",
      },
      spacing: {
        "base": "4px",
        "container-max": "1280px",
        "gutter": "20px",
        "lg": "24px",
        "md": "16px",
        "sm": "8px",
        "xl": "40px",
        "xs": "4px",
      },
      fontFamily: {
        "body": ["Tajawal", "sans-serif"],
        "body-lg": ["Tajawal"],
        "body-md": ["Tajawal"],
        "display-lg": ["Tajawal"],
        "headline-lg": ["Tajawal"],
        "headline-lg-mobile": ["Tajawal"],
        "label-md": ["Tajawal"],
        "label-sm": ["Tajawal"],
        "mono": ['JetBrains Mono', 'monospace'],
        "sans": ['Tajawal', 'sans-serif'],
        "tajawal": ['Tajawal', 'sans-serif'],
        "title": ["Tajawal", "sans-serif"],
        "title-md": ["Tajawal"],
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "full": "9999px",
        "lg": "0.5rem",
        "xl": "0.75rem",
      },
      boxShadow: {
        "card": '0 4px 6px -1px rgba(11, 28, 48, 0.03), 0 2px 4px -2px rgba(11, 28, 48, 0.03)',
        "drawer": '-8px 0 25px -5px rgba(11, 28, 48, 0.1), -2px 0 10px -6px rgba(11, 28, 48, 0.05)',
        "subtle": '0 1px 3px 0 rgba(11, 28, 48, 0.04), 0 1px 2px -1px rgba(11, 28, 48, 0.04)',
      }
    },
  },
  plugins: [],
};
